import { ThemeProvider } from "@/context/ThemeContext";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { AuthContextProvider } from "@/context/AuthContext";

export const metadata = {
  title: "Crypto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <AuthContextProvider>
            <Navbar />
            {children}
            <Footer />
          </AuthContextProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
